### ISSUE TITLE
Allow emojis in NIP05 field

### ISSUE THREAD

**Issue by gourcetools** [thebrandonlucas/nostrlytics#3]
![image](https://user-images.githubusercontent.com/120996278/222979557-3fbb1637-6334-47a5-9603-5412b4284618.png)
shame on me

**Comment by thebrandonlucas** [comment]
@gourcetools Thanks for pointing out. This one is tricky because there are so many different possibilities when introducing unicode, but from what I can tell the [Extended_Pictographic](https://stackoverflow.com/questions/18862256/how-to-detect-emoji-using-javascript) property escape is the way to go. I'll add this to the regex in an upcoming PR soon

**Comment by gourcetools** [comment]
<3

**Comment by thebrandonlucas** [comment]
@gourcetools let me know if this works! I'm not sure which relays you're on (is there a tool for that?), but you should be getting past the regex now
